### PR TITLE
Restyle prenet page and search

### PR DESCRIPTION
**Pull request by bonchovylkov**
Restyle of the Diode Network Explorer UI Update 1 following https://docs.google.com/document/d/1ruBLf5DUoee-bjXKV8jRyOR9Op_hXPK4X46MwG2aqUg/edit?ts=5f18709c#heading=h.itj0leo0v4to

### CODE REVIEW

**Review by dominicletz — COMMENTED** [review]
Selection_230

**Comment by dominicletz** [comment]
Selection_231

**Comment by dominicletz** [comment]
Selection_232

**Comment by dominicletz** [comment]
Selection_233

**Comment by dominicletz** [comment]
Selection_234

**Comment by dominicletz** [comment]
@hansr @bonchovylkov see the styling issues i marked above. So please fix this. IMHO you can just push against master here because it's website_dev. If you push to master here it will be visible on https://diodechain.github.io/website_dev/prenet/#/ easier to debug

**Comment by dominicletz** [comment]
I've rebased this branch against master and pushed into website_dev/master, so you can now see this deployed on https://diodechain.github.io/website_dev/ and directly compare to current https://diode.io/

Using scss for the /prenet/ is great, but @bonchovylkov  you need to keep the scope separated from the root pages or use two different style files. Otherwise the rest of the site is a mess and we can't merge this. Please compare pictures

Selection_235

**Comment by hansr** [comment]
@bonchovylkov Let us know when you've reviewed.  Once we have the styles sorted more closely, I'll provide additional feedback (e.g. the search bar should show up on every page)

**Comment by bonchovylkov** [comment]
Hi guys, the comments are fixed. I pushed them into master.
@hansr let me know about your additional feedback

**Comment by dominicletz** [comment]
Looks much better @bonchovylkov ! But there are still a few places that are broken. Seems the scope split is not quite complete. Screenshots:

Selection_238

Selection_239

And then it looks like the map broke in the process:

Selection_240

**Comment by dominicletz** [comment]
@bonchovylkov to fix this please put the scope higher on the body tag. e.g. `<body class="prenet">` and move the prenet scss, to it's own file in the layout directory and import from the global file like the other layouts. That will do it.

**Comment by bonchovylkov** [comment]
Thanks for tip @dominicletz
Now I think it looks much better. I checked the rest of the pages, they look okay, except for the `docs` - where the `header` looks stretched - but it is also like that in production, so I haven't fix it, since I am not sure if I have to.
The stretching comes these styles:
```
 body.docs {
  .container {
    width: 100%;
  }
```
from `_docs.scss`, but as I said it might be intentional.
Let me know if there is anything else.
Boncho

**Comment by dominicletz** [comment]
Hi @bonchovylkov , thanks for the update.

- style.scss still contains all prenet layout please move that to _scss//layouts/_prenet.scss
- please wrap all prenet css rules in `body.prenet { ...all rules... }` 
- gulp file now only generate prenet file but not rest-of-page file. please revert that
- In prenet/index.html don't need two css files

Maybe easier to explain in a video: https://www.youtube.com/watch?v=jqcmjIwTRy8

Best

**Comment by bonchovylkov** [comment]
@dominicletz - thanks for the clear explanation, I believe it should be okay now, but still, I am here if there is something else.

**Comment by dominicletz** [comment]
Cool, technically it all seems to fit now. @hansr please have a look the visuals, whether this is what you expected on the prenet pages

**Pull request closed without merging**
